# MQTT config
MQTT_HOST: localhost
MQTT_PORT: 1883
MQTT_TOPIC_NAME: apple
MQTT_USERNAME: ''
MQTT_PASSWORD: ''

DEBUG: false

HEALTHCHECK_ADDRESS: "localhost:8080"
# User storing findmy info
MAC_USER: ''
# Optionally provide the full path of Items.data
AIRTAGS_DATA_FILE: ''

# Runtime config
HOME_STREET_NAME: ''
HOME_STREET_ADDRESS: ''
AIRPODS_NAME: ''
