# MQTT config
MQTT_HOST: localhost
MQTT_PORT: 1883
MQTT_TOPIC_NAME: apple
MQTT_USERNAME: ''
MQTT_PASSWORD: ''

# User storing findmy info
MAC_USER: ''

# Runtime config
HOME_STREET_NAME: ''
HOME_STREET_ADDRESS: ''
AIRPODS_NAME: ''
